del output\*.html /q /s
del output\*.css /q /s
del output\*.txt /q /s
del output\*.jpg /q /s
del output\*.png /q /s
del output\*.tif /q /s
del output\*.svg /q /s
del output\*.save /q /s
del output\*.xml /q /s